language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - hhvm
install:
  - composer install
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose
