language: php

dist: trusty

php:
  - 7.1.3
  - 7.2

install:
  - composer install

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose
